### ISSUE TITLE
env definition in profile yaml

### ISSUE THREAD

**Issue by pocka** [pocka/docker-shepherd#23]
Add `env` and `env_file` property for node definition.
These parameters will be used in machine creation.

```yaml
version: '1'

nodes:
  foo:
    driver:
      name: virtualbox
    replicas: 1
    swarm: manager
    env:
      BAR: baz
    env_file:
      - ./secret.env
```
